server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql///test?serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.234.129
    lettuce:
      pool:
        max-active: 1000
        min-idle: 0
        max-idle: 1000
